openapi: 3.0.0

info:
  title: ""
  version: "%%%VERSION%%%"

paths:

  /session:
    get:
      summary: get a session
      description: returns session data according to an authToken.
      parameters:
        - in: header
          name: AuthToken
          examples:
            personToken:
              description: auth-token for person
              value: "p:0000000000000.00000000000"
            loginToken:
              description: auth-token for login (part I of 2-factor authorization only)
              value: "l:user000000000.test0000000"
            adminToken:
              description: auth-token for admin
              value: "a:user000000000.rw00000000"
      responses:
        "200":
          description: OK, get session data
          content:
            application/json:
              schema:
                $ref: './@components.spec.yml#/components/schemas/session'
              examples:
                personToken:
                  value:
                    token:  "static:person:sample_group_sample_user_xxx"
                    displayName: "sample_group/sample_user/xxx"
                    access:
                      test:  ["BOOKLET.SAMPLE"]
                    customTexts: {}
                    flags: []
                loginToken:
                  value:
                    token: "static:login:test"
                    displayName: "sample_group/sample_user"
                    access: {}
                    customTexts: {}
                    flags: ["codeRequired"]
                adminToken:
                  value:
                    token: "static:admin:super"
                    displayName: "super"
                    access:
                      superAdmin: []
                    customTexts: {}
                    flags: []
        "401":
          description: No token qualifies for authentication
        "410":
          description: Session Expired
        "500":
          description: Server Error


  /session/admin:
    put:
      summary: Start Admin Session
      description: Starts a Session as Admin by Username and password

      requestBody:
        content:
          application/json:
            schema:
              $ref: './@components.spec.yml#/components/schemas/login_request'

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './@components.spec.yml#/components/schemas/session'
              example:
                token: user000000000.0000000000
                displayName: super
                access:
                  workspaceAdmin: [1]
                  superAdmin: []
        "202":
          description: User has account but neither workspace nor super-admin privilige
        "400":
          description: Insufficent Crendetials
        "500":
          description: Server Error

  /session/login:
    put:
      summary: Start Login Session
      description: Starts a Session as Login by Username and password
        If the login requires a subsequent code insertion, you get a session with no access and the request for a
        password. Otherwise a set of accessable booklets will be retrieved.

      requestBody:
        content:
          application/json:
            schema:
              $ref: './@components.spec.yml#/components/schemas/login_request'
            example:
              name: test
              password: user123

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './@components.spec.yml#/components/schemas/session'
              example:
                token:  "static_login_sample_login"
                displayName: "sample_group/sample_user"
                access: {}
                customTexts: {} # due to https://github.com/iqb-berlin/testcenter-iqb-php/issues/53 get customTexts
                flags: ['codeRequired']
        "400":
          description: Insufficent Crendetials
#        "410": # - must be removed because test fails other wise... TODO find better solution
#          description: Session Expired
        "500":
          description: Server Error

  /session/person:
    put:
      summary: Start Person Session
      description: Starts a Session for a Person, on the basis of LoginToken (!)
        which is Part II of the Two-Factor Authentication for code-demanding logins.
        Get a token for a person belonging to a login, as defined in
        a `Testtakers.xml`-file, together with some information about this person

      parameters:
        - in: header
          name: AuthToken
          description: auth-token for a login-session
          example: "l:user000000000.test0000000"

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
            example:
              code: 'xxx'

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './@components.spec.yml#/components/schemas/session'
              example:
                token:  "static_person_xxx"
                displayName: "sample_group/sample_user/xxx"
                access:
                  test:
                    - ["BOOKLET.SAMPLE"]
                customTexts: {} # due to https://github.com/iqb-berlin/testcenter-iqb-php/issues/53 get customTexts
                flags: []
        "400":
          description: Insufficent Crendetials
        "410":
          description: Session Expired
        "500":
          description: Server Error
